version: '3.8'

networks:
  poupe_network:
    driver: bridge

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: poupe-db
    environment:
      SA_PASSWORD: "admin"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "admin", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - poupe_network
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: